name: Node App CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]  
  workflow_dispatch:
    
jobs:
  node-app-workflow:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js lts/fermium
        uses: actions/setup-node@v2
        with:
          node-version: lts/fermium
      - name: npm ci
        run: npm ci
      - name: format
        run: npm run prettier
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      
